# Site
repository: shkaushal/shkaushal.github.io
favicon: images/favicon.ico

# Personal info
name: Kaushal Kishor Sharma
title: Software Engineer | Python Developer
email: kaushalworkss@gmail.com
phone: +91-8003293018
website: shkaushal.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: kaushaltwt
github_username:  shkaushal
# dribbble_username:
# facebook_username:
# flickr_username:
instagram_username: kausha1_
linkedin_username: kaushal-kishor-sharma
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Hi, My name is Kaushal Kishor Sharma.
  I'm a Software Engineer, currently working at IBM. I aim to create a better experience for people and enhancing their lives by enabling intelligent technologies.
  I have graduated with a B.Tech in CSE from PDPM Indian Institute of Information Technology, Design & Manufacturing, Jabalpur in May 2021.

  I am most skilled in <mark>Python</mark> and <mark>Django</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
