# Site
repository: shkaushal/shkaushal.github.io
favicon: images/favicon.ico

# Personal info
name: Kaushal Kishor Sharma
title: Web Developer | Data Scientist | Competitive Programmer
email: kishorkaushal941@gmail.com
phone: +91-8003293018
website: shkaushal.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: sh_kaushal_
github_username:  shkaushal
# dribbble_username:
# facebook_username:
# flickr_username:
instagram_username: kausha1_
linkedin_username: kaushal-kishor-sharma
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  Hi, My name is Kaushal Kishor Sharma.
  I'm a Web Developer and a Data Scientist aiming to create a better experience for people and enhancing their lives by enabling intelligent technologies.
  I will be graduating with a B.Tech in CSE from PDPM Indian Institute of Information Technology, Design & Manufacturing, Jabalpur in May 2021.

  I am most skilled in <mark>Python</mark> and <mark>Django</mark>

  When I am not at my desk, I mostly spend my time outdoors. I do a lot of sports such as Volleyball, Badminton and Cricket.
  During the rest of my free time you will either find me reading some new tales or trying to cook a new dish.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
